### ISSUE TITLE
Why is the signer's certificate required to verify the signature?

### ISSUE THREAD

**Issue by markkohlmann** [falk-werner/zipsign#30]
If the signer's certificate is embedded in the comment why does it need to be provided to verify the signature?

**Comment by falk-werner** [comment]
Hello @markkohlmann,
thanks for your question. The short answer: it is not, but it is necessary to provide at least one trusted certificate. Therefore, the `-c` option is required during `zipsign verify`.

The use case for embedding the signers certificate is to complete the chain of trust when the signers certificate is unknown, but the root certificate is known. This is pretty much like validation of HTTPS works: your browser or operating system has a list of root certifcates which are used to verify the certificate of the actual website you visit.

You can achieve the same with zipsign. When building zipsign with tests enabled (default), a very basic PKI is provided in the `build/ca` subdirectory which can be used for testing:

```
build/ca/root-ca.crt                                      - Certificate of the root ca
build/ca/signing-ca.crt                                 - Certificate of the signing ca
build/ca/signing-ca/private/signing-ca.key - Private key of the signing ca
``` 

To sign some archive, you can use the signing ca and embed it's certificate:

    zipsign sign -f archive.zip -c build/ca/signing-ca.crt -p build/ca/signing-ca/private/signing-ca.key -e

Now you can verify the signature without providing the signing ca's certificate but by providing the root ca's certificate:

    zipsign verify -f archive.zip -c build/ca/root-ca.crt

Note that this will fail, if the `-e` option is omitted during signing, since the signers certificate is needed to complete the chain of trust.

Also note, that you always have to provide at least one certificate in order to verify the archive. All certificated inside the archive are considered untrusted. Otherwise we would be vulnerable for man-in-the-middle-attacs, where one takes the archives and re-signs it with his own certificates.

**Comment by markkohlmann** [comment]
Thank You @falk-werner for the prompt and detailed response,

What I was trying to use was just the `-k` parameter without `-c` which is automatically rejected by zipsign.  I hadn't realized that passing the root in as `-c` would work to verify the package.  Your example helped clarify that `-c` works with the root-ca.crt.  I was able to successfully verify a signed package that used `-e` and `-i` options with the root-ca.crt passed using `-c`.

Thank you for producing this great tool!
