### ISSUE TITLE
centos 7.5 make fail

### ISSUE THREAD

**Issue by Z000000** [falk-werner/zipsign#6]
OpenSSL which version?

**Comment by falk-werner** [comment]
You are right, zipsign does not compile against the OpenSSL version shipped with Cent OS 7. I think, OpenSSL 1.1.0 should work. I've tested with OpenSSL 1.1.1f on the development system. I've created a branch to build against Cent OS 7:

- [https://github.com/falk-werner/zipsign/tree/centos-7](https://github.com/falk-werner/zipsign/tree/centos-7)

It turned out that some minor fixes were needed to make it compile in Cent OS:
- install a newer cmake version
- install a newer OpenSSL version
- tweak default install directory of GoogleTest
- make gtest_main and gmock required in CMakeLists.txt
- check OpenSSL version in CMakeLists.txt
- fixed some headers (forgot to include <stdexcept> - why does this not fail on Ubuntu?)

You can try the Cent OS build using the provided Dockerfile:
````
docker build --rm --build-arg "USER_ID=`id -u`" --tag zipsign-centos -f docker/centos7.dockerfile .
````
